In [1]:
import numpy as np
a = np.array([[1,2,3,4],[5,6,7,8]])

In [2]:
b = [[1,2,3,4],[5,6,7,8]]

In [3]:
b

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [4]:
a[0,1]

2

In [5]:
b[0][1]

2

In [6]:
a[1:3]

array([[5, 6, 7, 8]])

In [7]:
a[0,1:3]

array([2, 3])

In [8]:
# 6와 7도 같이 출력
aa = a[0:2,1:3]

In [9]:
aa

array([[2, 3],
       [6, 7]])

In [10]:
c = np.array([[1,0],[0,0]])

In [11]:
c

array([[1, 0],
       [0, 0]])

In [12]:
aa * c

array([[2, 0],
       [0, 0]])

In [13]:
aa & c

array([[0, 0],
       [0, 0]])