In [1]:
import numpy as np

In [2]:
a = np.array([[1,2,3],[4,5,6]])

In [3]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
a.T # 행과 열의 축을 변경

array([[1, 4],
       [2, 5],
       [3, 6]])

In [6]:
block_L = np.array([
    [0,0,0,0],
 [0,1,0,0],
 [0,1,1,1],
 [0,0,0,0]])

In [7]:
block_L.T

array([[0, 0, 0, 0],
       [0, 1, 1, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0]])